### ISSUE TITLE
请问可以支持kitten3的闭源作品的反编译吗？

### ISSUE THREAD

**Issue by huogg001** [S-L-I-G-H-T-N-I-N-G/Kitten-4-Decompiler#4]
如题。
https://shequ.codemao.cn/work/1872329
https://shequ.codemao.cn/work/2584645
[学科游戏工作组](https://shequ.codemao.cn/user/591771)是个非常厉害的up主，可惜很早就离开了编程猫了。
他的很多作品都值得学习。虽然借助他的素材复刻了一个作品，但是比起原作还是有很多不足。
所以想拿原始的源码对比学习。

**Comment by alanchen32768** [comment]
可以啊

**Comment by huogg001** [comment]
kitten3闭源作品的错误代码如下：请输入要反编译的作品 ID：3357840
成功获取作品 [4;32mNO105_实际问题与方程[0m 的信息。
该作品由 [4;94mKITTEN3[0m  版本制作
成功获取作品 [4;32mNO105_实际问题与方程[0m 的编译文件 URL。
成功获取作品 [4;32mNO105_实际问题与方程[0m 的编译文件。
开始反编译，作品名称：[4;32mNO105_实际问题与方程[0m。
正在准备角色……
正在反编译角色……
[1;7;91m错误[0;1;91m：反编译失败。[0m
是否查看更多信息？(y/n)：y
Traceback (most recent call last):
  File "C:\turtle-editor2\resources\app.asar.unpacked\Python-win64\lib\xml\etree\ElementTree.py", line 1063, in _escape_cdata
    if "&" in text:
TypeError: argument of type 'int' is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\Main.py", line 46, in main
    decompiler.start()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 28, in start
    decompiler.start()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 109, in start
    getBlockDecompiler(compiledBlocks, self).start()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 136, in start
    self.children()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 180, in children
    childBlock = getBlockDecompiler(ChildBlocks[i], self.actor).start()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 136, in start
    self.children()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 180, in children
    childBlock = getBlockDecompiler(ChildBlocks[i], self.actor).start()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 135, in start
    self.nexts()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 168, in nexts
    nextBlock = getBlockDecompiler(self.compiled["next_block"], self.actor).start()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 135, in start
    self.nexts()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 168, in nexts
    nextBlock = getBlockDecompiler(self.compiled["next_block"], self.actor).start()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 138, in start
    self.params()
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\KittenDecompiler.py", line 220, in params
    self.shadows[name] = createShadow(paramType, paramBlock["id"], value)
  File "C:\Users\mrw\Desktop\Kitten-4-Decompiler-main\BlockShadowCreator.py", line 97, in createShadow
    return ElementTree.tostring(shadow, encoding='unicode')
  File "C:\turtle-editor2\resources\app.asar.unpacked\Python-win64\lib\xml\etree\ElementTree.py", line 1133, in tostring
    ElementTree(element).write(stream, encoding,
  File "C:\turtle-editor2\resources\app.asar.unpacked\Python-win64\lib\xml\etree\ElementTree.py", line 772, in write
    serialize(write, self._root, qnames, namespaces,
  File "C:\turtle-editor2\resources\app.asar.unpacked\Python-win64\lib\xml\etree\ElementTree.py", line 937, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "C:\turtle-editor2\resources\app.asar.unpacked\Python-win64\lib\xml\etree\ElementTree.py", line 935, in _serialize_xml
    write(_escape_cdata(text))
  File "C:\turtle-editor2\resources\app.asar.unpacked\Python-win64\lib\xml\etree\ElementTree.py", line 1071, in _escape_cdata
    _raise_serialization_error(text)
  File "C:\turtle-editor2\resources\app.asar.unpacked\Python-win64\lib\xml\etree\ElementTree.py", line 1053, in _raise_serialization_error
    raise TypeError(
TypeError: cannot serialize 1 (type int)

**Comment by alanchen32768** [comment]
稍等我看看

**Comment by S-LIGHTNING** [comment]
可以，但是近期没时间，寒假时可能会支持

**Comment by huogg001** [comment]
感谢！
